apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql-image
          name: mysql
          imagePullPolicy: Never
          ports:
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volume