apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftps-data
    port: 30000
    protocol: TCP
    targetPort: 30000
  - name: ftps-data1
    port: 30001
    protocol: TCP
    targetPort: 30001
  - name: ftps-data2
    port: 30002
    protocol: TCP
    targetPort: 30002
  - name: ftps-data3
    port: 30003
    protocol: TCP
    targetPort: 30003
  - name: ftps-data4
    port: 30004
    protocol: TCP
    targetPort: 30004
  - name: ftps-data5
    port: 30005
    protocol: TCP
    targetPort: 30005
  - name: ftps-data6
    port: 30006
    protocol: TCP
    targetPort: 30006
  - name: ftps-data7
    port: 30007
    protocol: TCP
    targetPort: 30007
  - name: ftps-data8
    port: 30008
    protocol: TCP
    targetPort: 30008
  - name: ftps-data9
    port: 30009
    protocol: TCP
    targetPort: 30009
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never